branches:
  only:
  - master
  - develop
  - travis
# <https://github.com/travis-ci/travis-ci/issues/3827#issuecomment-98114873>
language: java
jdk:
  - oraclejdk8
sudo: true
env:
  - NODE_VERSION=6.5
before_install:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
install:
  - nvm install $NODE_VERSION
  - ./scripts/install-dependencies.sh
  - npm install
  - sudo npm run config
script:
  - npm test
